# Generated by Django 4.0.2 on 2022-03-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='created_by',
            new_name='usuarios',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='favorito',
        ),
    ]
